name: dust
version: 0.0.1
description: Coverage-guided fuzz testing for Dart
authors:
  - Mike Fairhurst <mfairhurst@google.com>
homepage: https://github.com/MichaelRFairhurst/dust.dart
environment:
  sdk: '>=2.1.0 <3.0.0'
dependencies:
  args: '^1.5.2'
  vm_service_lib: '^3.21.0'
  test: '^1.6.5'
  quiver: '^2.0.3'
  collection: '^1.14.11'
  mockito: '^4.1.0'
  path: '^1.6.2'
