name: dust
version: 1.0.0-beta.8
description: Coverage-guided fuzz testing for Dart
authors:
  - Mike Fairhurst <mfairhurst@google.com>
homepage: https://github.com/MichaelRFairhurst/dust.dart
environment:
  sdk: '>=2.2.2 <3.0.0'
dependencies:
  meta: '^1.1.7'
  pedantic: '^1.8.0+1'
  crypto: '^2.0.6'
  args: '^1.5.2'
  vm_service: '^1.2.0'
  test: '^1.6.5'
  quiver: '^2.0.3'
  collection: '^1.14.11'
  mockito: '^4.1.0'
  path: '^1.6.2'
